const list = [

    { city: '上海', shopName: '沪太店', shopCode: '1001' },
    { city: '上海', shopName: '杨浦店', shopCode: '1003' },
    { city: '上海', shopName: '龙阳店', shopCode: '1004' },
    { city: '上海', shopName: '闵行店', shopCode: '1005' },
    { city: '上海', shopName: '徐泾店', shopCode: '1009' },
    { city: '上海', shopName: '莘庄店', shopCode: '1010' },
    { city: '上海', shopName: '青浦店', shopCode: 'C053' },
    { city: '上海', shopName: '闸北店', shopCode: '9101' },
    { city: '上海', shopName: '梅陇店', shopCode: '9102' },
    { city: '上海', shopName: '普陀店', shopCode: '9103' },
    { city: '上海', shopName: '金桥店', shopCode: '9104' },
    { city: '北京', shopName: '金四季店', shopCode: '1401' },
    { city: '北京', shopName: '九龙店', shopCode: '1402' },
    { city: '北京', shopName: '来广营店', shopCode: '1403' },
    { city: '北京', shopName: '立水桥店', shopCode: '1405' },
    { city: '北京', shopName: '马连道店', shopCode: '2801' },
    { city: '广州', shopName: '天河店', shopCode: '1801' },
    { city: '广州', shopName: '海珠店', shopCode: '1802' },
    { city: '深圳', shopName: '罗湖店', shopCode: '1301' },
    { city: '深圳', shopName: '南山店', shopCode: '1302' },
    { city: '深圳', shopName: '泰然店', shopCode: '1303' },
    { city: '深圳', shopName: '西丽店', shopCode: '1306' },
    { city: '杭州', shopName: '萧山店', shopCode: 'C061' },
    { city: '杭州', shopName: '临平店', shopCode: '3901' },
    { city: '杭州', shopName: '杭海店', shopCode: '1502' },
    { city: '杭州', shopName: '上塘店', shopCode: '9601' },
    { city: '重庆', shopName: '大渡口店', shopCode: '4301' },
    { city: '重庆', shopName: '龙湖店', shopCode: '2303' },
    { city: '成都', shopName: '金沙店', shopCode: '8701' },
    { city: '成都', shopName: '科华店', shopCode: '8702' },
    { city: '长沙', shopName: '梅溪店', shopCode: '4601' },
    { city: '长沙', shopName: '开福万达店', shopCode: 'C057' },
    { city: '南京', shopName: '雨花店', shopCode: '2003' },
    { city: '青岛', shopName: '市南店', shopCode: '1601' },
    { city: '青岛', shopName: '市北店', shopCode: '9401' },
    { city: '苏州', shopName: '园区店', shopCode: '1101' },
    { city: '常熟', shopName: '常熟万达店', shopCode: 'C049' },
    { city: '常州', shopName: '溧阳万达店', shopCode: 'C056' },
    { city: '滁州', shopName: '滁州店', shopCode: 'C064' },
    { city: '东莞', shopName: '第一国际店', shopCode: '2602' },
    { city: '福州', shopName: '陆庄店', shopCode: '1904' },
    { city: '湖州', shopName: '湖州店', shopCode: 'C046' },
    { city: '嘉兴', shopName: '经开万达店', shopCode: 'C052' },
    { city: '昆明', shopName: '世博店', shopCode: '1201' },
    { city: '马鞍山', shopName: '万达店', shopCode: 'C063' },
    { city: '南通', shopName: '万达店', shopCode: 'C055' },
    { city: '宁波', shopName: '万达店', shopCode: '3501' },
    { city: '石家庄', shopName: '万达店', shopCode: 'C054' },
    { city: '无锡', shopName: '新区店', shopCode: '2101' },
    { city: '无锡', shopName: '锡山店', shopCode: '2104' },
    { city: '无锡', shopName: '江阴万达店', shopCode: 'C048' },
    { city: '无锡', shopName: '宜兴万达店', shopCode: 'C065' },
    { city: '武汉', shopName: '武昌店', shopCode: '1701' },
    { city: '绍兴', shopName: '上虞店', shopCode: 'C058' },
    { city: '绍兴', shopName: '诸暨万达店', shopCode: 'C060' },
    { city: '厦门', shopName: '明发店', shopCode: '2501' },
    { city: '盐城', shopName: '中南店', shopCode: 'C051' },
    { city: '扬州', shopName: '扬州店', shopCode: 'C066' },


];
export default list;
