const obj = {
    北京: { shopCode: '1401', shopName: '北京金四季店' },
    常州: { shopCode: 'C056', shopName: '常州溧阳万达店' },
    滁州: { shopCode: 'C064', shopName: '安徽滁州店' },
    长沙: { shopCode: '4601', shopName: '长沙梅溪店' },
    重庆: { shopCode: '2303', shopName: '重庆龙湖店' },
    成都: { shopCode: '8702', shopName: '成都科华店' },
    东莞: { shopCode: '2602', shopName: '东莞第一国际店' },
    福州: { shopCode: '1904', shopName: '福州陆庄店' },
    广州: { shopCode: '1801', shopName: '广州天河店' },
    杭州: { shopCode: '9601', shopName: '杭州上塘店' },
    湖州: { shopCode: 'C046', shopName: '湖州店' },
    嘉兴: { shopCode: '8810', shopName: '嘉兴经开万达店' },
    昆明: { shopCode: '1201', shopName: '昆明世博店' },
    马鞍山: { shopCode: 'C063', shopName: '马鞍山万达店' },
    南京: { shopCode: '2003', shopName: '南京雨花店' },
    南通: { shopCode: 'C055', shopName: '南通万达店' },
    宁波: { shopCode: '3501', shopName: '宁波万达店' },
    青岛: { shopCode: '1601', shopName: '青岛市南店' },
    石家庄: { shopCode: 'C054', shopName: '石家庄万达店' },
    上海: { shopCode: '1001', shopName: '上海沪太店' },
    苏州: { shopCode: '1101', shopName: '苏州园区店' },
    绍兴: { shopCode: 'C058', shopName: '绍兴上虞店' },
    深圳: { shopCode: '1301', shopName: '深圳罗湖店' },
    无锡: { shopCode: '2101', shopName: '新区店' },
    武汉: { shopCode: '1701', shopName: '武昌店' },
    厦门: { shopCode: '2501', shopName: '厦门明发店' },
    盐城: { shopCode: 'C051', shopName: '盐城中南店' },
    扬州: { shopCode: '8881', shopName: '扬州店' },
};


export default obj;
